### ISSUE TITLE
bug: ensure Setting Library is installed or handle missing dependency

### ISSUE THREAD

**Issue by datamweb** [warcooft/codeigniter4-multi-smtp-config#1]
"If you're using the setting library in your PHP project, add it to the composer.json file. If you prefer not to, you can check at runtime if the library is installed and throw an exception if it's missing:"

```php
    throw new Exception("The 'setting' library is required but not installed. Please add it to your dependencies or install it manually.");
```
OR 
```json
{
    "require": {
        "codeigniter4/settings": "^2.1"
    }
}
```

https://github.com/warcooft/codeigniter4-multi-smtp-config/blob/5f108e42beb97a70263f4280f1f27eccc584b88d/src/Helpers/multi_email_helper.php#L26

**Comment by warcooft** [comment]
@datamweb Thank you, yes this is very necessary.
